#!/usr/bin/env bash
# ════════════════════════════════════════════════════════════════════════
# fix-nginx-mjs-mime.sh
#
# Some nginx defaults serve .mjs files as application/octet-stream which
# causes browsers to reject them when loaded as JavaScript modules.
# This script adds a `types { application/javascript mjs; }` block to
# /etc/nginx/conf.d/mjs-mime.conf so .mjs is served correctly.
#
# Symptom this fixes: "Failed to fetch dynamically imported module" or
# "Setting up fake worker failed" errors when the browser tries to load
# .mjs assets (e.g. PDF.js worker).
#
# Usage (on the frontend host):
#   sudo bash fix-nginx-mjs-mime.sh
# ════════════════════════════════════════════════════════════════════════
set -euo pipefail

if [ "$EUID" -ne 0 ]; then
    echo "❌ Must run as root (sudo)."
    exit 1
fi

CONF=/etc/nginx/conf.d/mjs-mime.conf

cat > "$CONF" <<'EOF'
# Auto-generated by fix-nginx-mjs-mime.sh
# Ensure ECMAScript module files (.mjs) are served as JavaScript so
# browsers (and PDF.js) accept them when loaded with `new Worker()`
# or dynamic `import()`.
types {
    application/javascript  mjs;
}
EOF

echo "→ Wrote $CONF"
echo "→ Validating nginx config…"
nginx -t

echo "→ Reloading nginx…"
systemctl reload nginx

echo "✅ Done. .mjs files will now be served as application/javascript."
